# Generated by Django 6.0 on 2026-01-06 13:16

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
                ('identifier', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('otp', models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{4,6}$', 'OTP must be 4-6 digits')])),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_expire', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('handler', 'Handler')], default='handler', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ManyToManyField(blank=True, related_name='members', to='shop.shop')),
            ],
            options={
                'verbose_name': 'Admin',
                'db_table': 'admin',
            },
        ),
    ]
