# Generated by Django 6.0 on 2026-01-06 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop/logos/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='shop/covers/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='shop/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='shop.shop')),
            ],
            options={
                'verbose_name': 'images',
                'db_table': 'image',
            },
        ),
    ]
