# Generated by Django 6.0 on 2025-12-24 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'db_table': 'shops',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.EmailField(max_length=254, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pending Registration',
                'db_table': 'preregistration',
                'indexes': [models.Index(fields=['created_at'], name='preregistra_created_809fbd_idx'), models.Index(fields=['identifier'], name='preregistra_identif_30b0ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/logos/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='shops/covers/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='shops/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop Images',
                'db_table': 'shop_branding',
            },
        ),
        migrations.CreateModel(
            name='ShopSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop Social',
                'db_table': 'shop_socials',
            },
        ),
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop Detail',
                'db_table': 'shop_details',
                'indexes': [models.Index(fields=['category'], name='shop_detail_categor_38b8ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
                ('identifier', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('otp', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_expire', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('handler', 'Handler')], default='handler', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop Member',
                'db_table': 'shop_members',
                'indexes': [models.Index(fields=['identifier', 'shop'], name='shop_member_identif_79ee31_idx')],
                'unique_together': {('shop', 'identifier')},
            },
        ),
    ]
