# Generated by Django 6.0 on 2025-12-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
