# Generated by Django 6.0 on 2025-12-22 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('grocery', 'Grocery'), ('beauty', 'Beauty & Health'), ('home', 'Home & Garden'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_covers/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='shop_profiles/'),
        ),
    ]
