# Generated by Django 6.0 on 2025-12-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_category_shop_cover_photo_shop_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopmember',
            name='role',
            field=models.CharField(default='handler', max_length=10),
        ),
    ]
