# Generated by Django 6.0 on 2025-12-22 19:06

import shops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_category_alter_shopmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models.get_cover_path),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models.get_logo_path),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=shops.models.get_profile_path),
        ),
    ]
