# Generated by Django 6.0 on 2026-01-06 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(default='new Shop', max_length=255)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop.shop')),
            ],
            options={
                'verbose_name': 'detail',
                'db_table': 'details',
                'indexes': [models.Index(fields=['category'], name='details_categor_3e7a3f_idx')],
            },
        ),
    ]
