# Generated by Django 6.0 on 2026-01-05 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(default='', max_length=6)),
                ('otp_expires_at', models.DateTimeField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pre Registration',
                'verbose_name_plural': 'Pre Registrations',
                'db_table': 'pre_registration',
            },
        ),
    ]
