# Generated by Django 6.0 on 2026-01-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_shop'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='product_slug_b8980b_idx',
            old_name='products_slug_5e91f2_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_sku_afe0af_idx',
            old_name='products_sku_fe2039_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
